# Generated by Django 4.1.1 on 2023-02-23 06:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSurveyData',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='Acess_images')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('projectName', models.TextField(blank=True)),
                ('sitename', models.TextField(blank=True)),
                ('sitecode', models.TextField(blank=True)),
                ('longitude', models.TextField(blank=True)),
                ('latitude', models.TextField(blank=True)),
                ('cabinetLocation', models.TextField(blank=True)),
                ('siteType', models.TextField(blank=True)),
                ('plinthRequired', models.TextField(blank=True)),
                ('infrastructureType', models.TextField(blank=True)),
                ('infrastructureOwner', models.TextField(blank=True)),
                ('infrastructureHeight', models.TextField(blank=True)),
                ('spaceAntennaRequirement', models.TextField(blank=True)),
                ('gsm900AntennaHeightS1', models.TextField(blank=True)),
                ('gsm900AntennaHeightS2', models.TextField(blank=True)),
                ('gsm900AntennaHeightS3', models.TextField(blank=True)),
                ('gsm900AntennaHeightS4', models.TextField(blank=True)),
                ('gsm900AntennaAzimuthS1', models.TextField(blank=True)),
                ('gsm900AntennaAzimuthS2', models.TextField(blank=True)),
                ('gsm900AntennaAzimuthS3', models.TextField(blank=True)),
                ('gsm900AntennaAzimuthS4', models.TextField(blank=True)),
                ('gsm1800AntennaHeightS1', models.TextField(blank=True)),
                ('gsm1800AntennaHeightS2', models.TextField(blank=True)),
                ('gsm1800AntennaHeightS3', models.TextField(blank=True)),
                ('gsm1800AntennaHeightS4', models.TextField(blank=True)),
                ('gsm1800AntennaAzimuthS1', models.TextField(blank=True)),
                ('gsm1800AntennaAzimuthS2', models.TextField(blank=True)),
                ('gsm1800AntennaAzimuthS3', models.TextField(blank=True)),
                ('gsm1800AntennaAzimuthS4', models.TextField(blank=True)),
                ('lte1800AntennaHeightS1', models.TextField(blank=True)),
                ('lte1800AntennaHeightS2', models.TextField(blank=True)),
                ('lte1800AntennaHeightS3', models.TextField(blank=True)),
                ('lte1800AntennaHeightS4', models.TextField(blank=True)),
                ('lte1800AntennaAzimuthS1', models.TextField(blank=True)),
                ('lte1800AntennaAzimuthS2', models.TextField(blank=True)),
                ('lte1800AntennaAzimuthS3', models.TextField(blank=True)),
                ('lte1800AntennaAzimuthS4', models.TextField(blank=True)),
                ('u2100AntennaHeightS1', models.TextField(blank=True)),
                ('u2100AntennaHeightS2', models.TextField(blank=True)),
                ('u2100AntennaHeightS3', models.TextField(blank=True)),
                ('u2100AntennaHeightS4', models.TextField(blank=True)),
                ('u2100AntennaAzimuthS1', models.TextField(blank=True)),
                ('u2100AntennaAzimuthS2', models.TextField(blank=True)),
                ('u2100AntennaAzimuthS3', models.TextField(blank=True)),
                ('u2100AntennaAzimuthS4', models.TextField(blank=True)),
                ('lte2600AntennaHeightS1', models.TextField(blank=True)),
                ('lte2600AntennaHeightS2', models.TextField(blank=True)),
                ('lte2600AntennaHeightS3', models.TextField(blank=True)),
                ('lte2600AntennaHeightS4', models.TextField(blank=True)),
                ('lte2600AntennaAzimuthS1', models.TextField(blank=True)),
                ('lte2600AntennaAzimuthS2', models.TextField(blank=True)),
                ('lte2600AntennaAzimuthS3', models.TextField(blank=True)),
                ('lte2600AntennaAzimuthS4', models.TextField(blank=True)),
                ('groundSpaceComment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
