# Generated by Django 4.1.1 on 2023-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesssurveydata_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessNewSiteSurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.TextField(blank=True)),
                ('sitename', models.TextField(blank=True)),
                ('sitecode', models.TextField(blank=True)),
                ('surveyDate', models.TextField(blank=True)),
                ('opt1LocationController', models.TextField(blank=True)),
                ('opt1TowerController', models.TextField(blank=True)),
                ('opt1AccessController', models.TextField(blank=True)),
                ('opt1PowerController', models.TextField(blank=True)),
                ('opt1LongitudeController', models.TextField(blank=True)),
                ('opt1LatitudeController', models.TextField(blank=True)),
                ('opt2LocationController', models.TextField(blank=True)),
                ('opt2TowerController', models.TextField(blank=True)),
                ('opt2AccessController', models.TextField(blank=True)),
                ('opt2PowerController', models.TextField(blank=True)),
                ('opt2LongitudeController', models.TextField(blank=True)),
                ('opt2LatitudeController', models.TextField(blank=True)),
                ('opt3LocationController', models.TextField(blank=True)),
                ('opt3TowerController', models.TextField(blank=True)),
                ('opt3AccessController', models.TextField(blank=True)),
                ('opt3PowerController', models.TextField(blank=True)),
                ('opt3LongitudeController', models.TextField(blank=True)),
                ('opt3LatitudeController', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
            ],
        ),
    ]
