# Generated by Django 4.1.1 on 2023-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accessnewsitesurveydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='Owner',
            field=models.TextField(blank=True),
        ),
    ]
