# Generated by Django 4.1.1 on 2023-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accessnewsitesurveydata_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessnewsitesurveydata',
            old_name='Owner',
            new_name='opt1Owner',
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='opt2Owner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='opt3Owner',
            field=models.TextField(blank=True),
        ),
    ]
