# Generated by Django 4.1.1 on 2023-03-15 07:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_owner_accessnewsitesurveydata_opt1owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesssurveydata',
            name='image',
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
