# Generated by Django 4.1.1 on 2023-03-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_accesssurveydata_image2_accesssurveydata_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesssurveydata',
            name='image1',
        ),
    ]
