# Generated by Django 4.1.1 on 2023-03-15 09:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_accesssurveydata_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssurveydata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='image3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
