# Generated by Django 4.1.1 on 2023-03-15 10:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_accesssurveydata_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesssurveydata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
