# Generated by Django 4.1.1 on 2023-03-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_accesssurveydata_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesssurveydata',
            name='image3',
        ),
    ]
