# Generated by Django 4.1.1 on 2023-03-19 19:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_accesssurveydata_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
