# Generated by Django 4.2 on 2023-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_accessnewsitesurveydata_image6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessnewsitesurveydata',
            old_name='opt1Owner',
            new_name='opt1ownerName',
        ),
        migrations.RenameField(
            model_name='accessnewsitesurveydata',
            old_name='opt2Owner',
            new_name='opt2ownerName',
        ),
        migrations.RenameField(
            model_name='accessnewsitesurveydata',
            old_name='opt3Owner',
            new_name='opt3ownerName',
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='connectivityRep',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='opt1equipmentComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='opt2equipmentComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='opt3equipmentComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='saqRep',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='siteDescription',
            field=models.TextField(blank=True),
        ),
    ]
