# Generated by Django 4.2 on 2023-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_opt1owner_accessnewsitesurveydata_opt1ownername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='opt1ownerName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='opt2ownerName',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='opt3ownerName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='projectName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='saqRep',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='sitecode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='sitename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='surveyDate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
