# Generated by Django 4.2 on 2023-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_accessnewsitesurveydata_opt1ownername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesssurveydata',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='cabinetLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='plinthRequired',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='projectName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='siteType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='sitecode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accesssurveydata',
            name='sitename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
