# Generated by Django 4.2 on 2023-05-18 11:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_accesssurveydata_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessnewsitesurveydata',
            name='report_type',
            field=models.CharField(blank=True, default='New Site', editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AddField(
            model_name='accesssurveydata',
            name='report_type',
            field=models.CharField(blank=True, default='Existing Site', editable=False, max_length=100, null=True),
        ),
    ]
