# Generated by Django 4.2 on 2023-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_accessnewsitesurveydata_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesssurveydata',
            name='report_type',
            field=models.CharField(blank=True, default='Existing Site', editable=False, max_length=100),
        ),
    ]
