# Generated by Django 4.2 on 2023-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_accesssurveydata_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='report_type',
            field=models.CharField(blank=True, default='New Site', editable=False, max_length=100),
        ),
    ]
