# Generated by Django 4.2 on 2023-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_accessnewsitesurveydata_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessnewsitesurveydata',
            name='connectivityRep',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
