# Generated by Django 4.2 on 2023-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_accessnewsitesurveydata_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesssurveydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
