# Generated by Django 4.1.1 on 2023-02-23 06:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivitySurveyData',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='Connectivity_images')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('projectName', models.TextField(blank=True)),
                ('sitename', models.TextField(blank=True)),
                ('sitecode', models.TextField(blank=True)),
                ('lit_fibre_pop', models.TextField(blank=True)),
                ('atn_type', models.TextField(blank=True)),
                ('atn_location', models.TextField(blank=True)),
                ('free_atn_electrical_ports', models.TextField(blank=True)),
                ('free_atn_optical_ports', models.TextField(blank=True)),
                ('cable_length', models.TextField(blank=True)),
                ('idu_type', models.TextField(blank=True)),
                ('microwave_location', models.TextField(blank=True)),
                ('free_microwave_electrical_ports', models.TextField(blank=True)),
                ('free_microwave_optical_ports', models.TextField(blank=True)),
                ('microwave_cable_length', models.TextField(blank=True)),
                ('move_atn_or_mw_to_cabinet', models.TextField(blank=True)),
                ('duct_cable_required', models.TextField(blank=True)),
                ('duct_length_required', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
