# Generated by Django 4.1.1 on 2023-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0002_rename_username_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
