# Generated by Django 4.1.1 on 2023-02-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0003_connectivitysurveydata_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core2.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
