# Generated by Django 4.1.1 on 2023-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0004_alter_connectivitysurveydata_author_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
