# Generated by Django 4.1.1 on 2023-02-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0005_alter_connectivitysurveydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core2.profile'),
        ),
    ]
