# Generated by Django 4.1.1 on 2023-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='imageConnectivityFiles',
            field=models.TextField(blank=True),
        ),
    ]
