# Generated by Django 4.1.1 on 2023-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0009_connectivitysurveydata_imageconnectivityfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='imageConnectivityFiles',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
