# Generated by Django 4.1.1 on 2023-02-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0010_alter_connectivitysurveydata_imageconnectivityfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core2.profile'),
        ),
    ]
