# Generated by Django 4.2 on 2023-05-09 12:53

import core2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0012_alter_connectivitysurveydata_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectivitysurveydata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='connectivitysurveydata',
            name='imageConnectivityFiles',
        ),
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to=core2.models.upload_to),
        ),
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core2.models.upload_to),
        ),
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core2.models.upload_to),
        ),
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core2.models.upload_to),
        ),
        migrations.AddField(
            model_name='connectivitysurveydata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=core2.models.upload_to),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='projectName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='sitecode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='sitename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
