# Generated by Django 4.2 on 2023-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0013_remove_connectivitysurveydata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='free_atn_electrical_ports',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='free_atn_optical_ports',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='free_microwave_electrical_ports',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='free_microwave_optical_ports',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
