# Generated by Django 4.2 on 2023-05-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0014_alter_connectivitysurveydata_free_atn_electrical_ports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='duct_length_required',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='microwave_cable_length',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
