# Generated by Django 4.2 on 2023-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0015_alter_connectivitysurveydata_duct_length_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='move_atn_or_mw_to_cabinet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
