# Generated by Django 4.2 on 2023-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0016_alter_connectivitysurveydata_move_atn_or_mw_to_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivitysurveydata',
            name='atn_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
